from fastapi import APIRouter, HTTPException, Response
from database import db
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.platypus import Table, TableStyle
from datetime import datetime
import io

router = APIRouter()

def get_db_cursor():
    if not db.is_connected():
        db.reconnect()
    return db.cursor(dictionary=True)

@router.get("/generate/{barcode}")
def generate_report(barcode: str):
    cursor = get_db_cursor()
    
    # 1. Fetch Patient & Order Info
    cursor.execute("""
        SELECT * FROM samples WHERE barcode = %s
    """, (barcode,))
    sample = cursor.fetchone()
    
    if not sample:
        raise HTTPException(status_code=404, detail="Sample not found")

    # 2. Fetch Results
    cursor.execute("""
        SELECT * FROM results WHERE sample_barcode = %s
    """, (barcode,))
    results = cursor.fetchall()

    # 3. Create PDF in Memory
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    # --- HEADER ---
    c.setFont("Helvetica-Bold", 18)
    c.drawString(50, height - 50, "EWC LIS Laboratory")
    
    c.setFont("Helvetica", 10)
    c.drawString(50, height - 65, "Kathmandu, Nepal | Phone: +977-9800000000")
    c.line(50, height - 75, width - 50, height - 75)

    # --- PATIENT INFO ---
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, height - 100, "Patient Report")
    
    c.setFont("Helvetica", 10)
    y_pos = height - 120
    # Use .get() to avoid errors if key is missing, or fallback to empty string
    pat_name = sample.get('patient_name', 'Unknown')
    bar_code = sample.get('barcode', 'Unknown')
    col_time = sample.get('collection_time', 'Unknown')
    status = sample.get('status', 'Unknown')

    c.drawString(50, y_pos, f"Name: {pat_name}")
    c.drawString(300, y_pos, f"Barcode: {bar_code}")
    
    y_pos -= 15
    c.drawString(50, y_pos, f"Collected: {col_time}")
    c.drawString(300, y_pos, f"Status: {status}")

    # --- RESULTS TABLE ---
    # Header Row
    data = [["Test Name", "Result", "Unit", "Ref. Range", "Flag"]]
    
    for r in results:
        data.append([
            r.get('test_name', ''),
            str(r.get('result_value', '')),
            r.get('unit') or "",
            r.get('ref_range') or "",
            r.get('flag') or ""
        ])

    if len(data) > 1: # Only draw table if there are results
        table = Table(data, colWidths=[150, 80, 60, 100, 60])
        
        # Styling
        style = TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.navy),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ])
        table.setStyle(style)

        # Draw Table
        table.wrapOn(c, width, height)
        # Calculate Y position dynamically based on number of rows
        table.drawOn(c, 50, y_pos - 50 - (len(data) * 20))
    else:
        c.drawString(50, y_pos - 50, "No results found for this sample.")

    # --- FOOTER ---
    c.setFont("Helvetica-Oblique", 8)
    c.drawString(50, 30, f"Generated by EWC LIS | Dev: Kritan Nepal | {datetime.now().strftime('%Y-%m-%d %H:%M')}")

    c.showPage()
    c.save()

    buffer.seek(0)
    return Response(content=buffer.getvalue(), media_type="application/pdf")